/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.dao.UsuarioDAO;
import br.ulbra.model.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class FormDashboard extends javax.swing.JFrame {

    /**
     * Creates new form FormDashboard
     */
    public FormDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        itmCadUsuario = new javax.swing.JMenuItem();
        itmPredefinidos = new javax.swing.JMenuItem();
        itmSair = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itmConsUsuario = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itmTodos = new javax.swing.JMenuItem();
        itmRemUsuario = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SistemaPoo");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(10, 10, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/java.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Java");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jMenu4.setText("Cadastro");

        itmCadUsuario.setText("Usuário");
        itmCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadUsuarioActionPerformed(evt);
            }
        });
        jMenu4.add(itmCadUsuario);

        itmPredefinidos.setText("Predefinidos");
        itmPredefinidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPredefinidosActionPerformed(evt);
            }
        });
        jMenu4.add(itmPredefinidos);

        itmSair.setText("Sair");
        itmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSairActionPerformed(evt);
            }
        });
        jMenu4.add(itmSair);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Consulta");

        itmConsUsuario.setText("Tabela");
        itmConsUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmConsUsuarioActionPerformed(evt);
            }
        });
        jMenu5.add(itmConsUsuario);

        jMenuBar2.add(jMenu5);

        jMenu1.setText("Remover");

        itmTodos.setText("Todos");
        itmTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmTodosActionPerformed(evt);
            }
        });
        jMenu1.add(itmTodos);

        itmRemUsuario.setText("Usuario");
        itmRemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRemUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(itmRemUsuario);

        jMenuBar2.add(jMenu1);

        jMenu6.setText("Sobre");

        jMenuItem5.setText("SIstema");
        jMenu6.add(jMenuItem5);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmTodosActionPerformed
        try {
            UsuarioDAO ud = new UsuarioDAO();
            ud.deleteAllUsers();
            JOptionPane.showMessageDialog(null, "Todos os usuários forma removidos!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
    }//GEN-LAST:event_itmTodosActionPerformed

    private void itmRemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRemUsuarioActionPerformed
        int id = Integer.parseInt(JOptionPane.showInputDialog("Qual é o ID do usuário à remover?"));
        try {
            UsuarioDAO ud = new UsuarioDAO();
            ud.deleteUser(id);
            JOptionPane.showMessageDialog(null, "Usuário removido!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
    }//GEN-LAST:event_itmRemUsuarioActionPerformed

    private void itmCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadUsuarioActionPerformed
        new FormCadastro().setVisible(true); 
        setLocationRelativeTo(null);
    }//GEN-LAST:event_itmCadUsuarioActionPerformed

    private void itmPredefinidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPredefinidosActionPerformed
        try {
            UsuarioDAO ud = new UsuarioDAO();
            ud.create(new Usuario("Bento", "bento@outlook.com", "senha1", "Masculino", "51988223344"));
            ud.create(new Usuario("Anita", "anita@gmail.com", "senha2", "Feminino", "51977112233"));
            ud.create(new Usuario("Gumersindo", "gume@bol.com.br", "senha3", "Masculino", "51966009988"));
            ud.create(new Usuario("Prenda", "prenda@terra.com.br", "senha4", "Feminino", "51955887766"));
            ud.create(new Usuario("Bagual", "bagual@uol.com.br", "senha5", "Masculino", "51944776655"));
            ud.create(new Usuario("Mariana", "mari@gmail.com", "senha6", "Feminino", "51933665544"));
            ud.create(new Usuario("Tchê", "tche@yahoo.com", "senha7", "Masculino", "51922554433"));
            ud.create(new Usuario("Bibiana", "bibi@ig.com.br", "senha8", "Feminino", "51911443322"));
            ud.create(new Usuario("Loco", "loco@gmail.com", "senha9", "Masculino", "51999332211"));
            ud.create(new Usuario("Guria", "guria@hotmail.com", "senha10", "Feminino", "51988221100"));
            ud.create(new Usuario("Indio", "indio@gmail.com", "senha11", "Masculino", "51977110099"));
            ud.create(new Usuario(" prenda_minha", "minha@gmail.com", "senha12", "Feminino", "51966008877"));
            ud.create(new Usuario("Fandango", "fanda@outlook.com", "senha13", "Masculino", "51955997766"));
            ud.create(new Usuario("Rosita", "rosita@gmail.com", "senha14", "Feminino", "51944886655"));
            ud.create(new Usuario("Campeiro", "campo@terra.com.br", "senha15", "Masculino", "51933775544"));
            ud.create(new Usuario("Luzia", "luzia@uol.com.br", "senha16", "Feminino", "51922664433"));
            ud.create(new Usuario("Pala", "pala@yahoo.com", "senha17", "Masculino", "51911553322"));
            ud.create(new Usuario("Teiniaguá", "teinia@gmail.com", "senha18", "Feminino", "51900442211"));
            JOptionPane.showMessageDialog(null, "Banco alimentado!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
    }//GEN-LAST:event_itmPredefinidosActionPerformed

    private void itmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSairActionPerformed
        dispose();
    }//GEN-LAST:event_itmSairActionPerformed

    private void itmConsUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmConsUsuarioActionPerformed
        try {
            new FormListagem().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FormDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itmConsUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmCadUsuario;
    private javax.swing.JMenuItem itmConsUsuario;
    private javax.swing.JMenuItem itmPredefinidos;
    private javax.swing.JMenuItem itmRemUsuario;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JMenuItem itmTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
